name: tarfa
channels:
  - conda-forge
  - bioconda
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.32.2=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - ftfy=6.1.3=pyhd8ed1ab_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.5=py310hc7909c9_1
  - grpcio=1.62.2=py310h1b8f574_0
  - huggingface_hub=0.23.3=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_3
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libdeflate=1.20=hd590300_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_8
  - libgfortran-ng=13.2.0=h69a702a_8
  - libgfortran5=13.2.0=h3d2ce59_8
  - libgit2=1.8.1=he8d1d4c_1
  - libgomp=13.2.0=h77fa898_8
  - libgrpc=1.62.2=h15f2491_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=22_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_8
  - libtiff=4.6.0=h1dd3fc0_3
  - libtorch=2.3.0=cpu_generic_h970db74_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.5=h59595ed_0
  - nomkl=1.0=h5ca1d4c_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=pyhd8ed1ab_0
  - pcre2=10.44=h0f59acf_0
  - pgzip=0.3.5=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - protobuf=4.25.3=py310ha8c1f0e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.22=pyhd8ed1ab_0
  - pygit2=1.15.0=py310hc51659f_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=hd12c33a_0_cpython
  - python_abi=3.10=4_cp310
  - pyyaml=6.0.1=py310h2372a71_1
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - regex=2024.5.15=py310hc51659f_0
  - safetensors=0.4.3=py310hcb5633a_0
  - scipy=1.13.1=py310h93e2701_0
  - setuptools=70.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sympy=1.12=pypyh9d50eac_103
  - tensorboard=2.17.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h75e40e8_1
  - tensorboardx=2.6.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.4=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.19.2=pyhd8ed1ab_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - adversarial-robustness-toolbox==1.18.0
    - advertorch==0.2.3
    - altair==5.3.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.4.1
    - attrs==23.2.0
    - bleach==6.1.0
    - blinker==1.8.2
    - blis==0.7.11
    - braceexpand==0.1.7
    - cachetools==5.3.3
    - catalogue==2.0.10
    - cfgv==3.4.0
    - chardet==4.0.0
    - click==8.1.7
    - clip==1.0
    - cloudpathlib==0.18.1
    - confection==0.1.5
    - contexttimer==0.3.3
    - contourpy==1.2.1
    - cycler==0.12.1
    - cymem==2.0.8
    - decorator==5.1.1
    - decord==0.6.0
    - dill==0.3.8
    - distlib==0.3.8
    - eagerpy==0.30.0
    - einops==0.8.0
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fairscale==0.4.4
    - ffmpeg-python==0.2.0
    - filelock==3.13.1
    - fonttools==4.53.0
    - foolbox==3.3.4
    - fsspec==2024.2.0
    - future==1.0.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - identify==2.5.36
    - idna==2.10
    - imageio==2.34.1
    - iopath==0.1.10
    - ipython==8.25.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.4.2
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - kaggle==1.6.14
    - kiwisolver==1.4.5
    - kornia==0.7.2
    - kornia-rs==0.1.3
    - langcodes==3.4.0
    - language-data==1.2.0
    - lazy-loader==0.4
    - lxml==5.2.2
    - marisa-trie==1.2.0
    - markdown-it-py==3.0.0
    - matplotlib==3.9.0
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - multiprocess==0.70.16
    - murmurhash==1.0.10
    - networkx==3.2.1
    - nodeenv==1.9.1
    - numpy==1.26.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nvtx-cu11==11.8.86
    - omegaconf==2.3.0
    - opencv-python==4.10.0.82
    - opencv-python-headless==4.5.5.64
    - opendatasets==0.1.22
    - pandas==2.2.2
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==10.2.0
    - platformdirs==4.2.2
    - plotly==5.22.0
    - portalocker==2.8.2
    - pre-commit==3.7.1
    - preshed==3.0.9
    - prompt-toolkit==3.0.47
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==16.1.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.7
    - pydantic==2.7.4
    - pydantic-core==2.18.4
    - pydeck==0.9.1
    - pygments==2.18.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-magic==0.4.27
    - python-slugify==8.0.4
    - pytz==2024.1
    - referencing==0.35.1
    - requests==2.25.1
    - rich==13.7.1
    - rpds-py==0.18.1
    - salesforce-lavis==1.0.2
    - scikit-image==0.23.2
    - scikit-learn==1.5.0
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - shellingham==1.5.4
    - smart-open==7.0.4
    - smmap==5.0.1
    - spacy==3.7.5
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.3
    - streamlit==1.35.0
    - tenacity==8.3.0
    - text-unidecode==1.3
    - thinc==8.2.4
    - threadpoolctl==3.5.0
    - tifffile==2024.5.22
    - timm==0.4.12
    - tokenizers==0.13.3
    - toml==0.10.2
    - toolz==0.12.1
    - torch==2.3.0+cu118
    - torchattacks==3.5.1
    - torchsummary==1.5.1
    - torchvision==0.18.0+cu118
    - tornado==6.4.1
    - traitlets==5.14.3
    - transformers==4.26.1
    - triton==2.3.0
    - typer==0.12.3
    - typing-extensions==4.9.0
    - tzdata==2024.1
    - urllib3==1.26.19
    - virtualenv==20.26.2
    - wasabi==1.1.3
    - watchdog==4.0.1
    - weasel==0.4.1
    - webdataset==0.2.86
    - webencodings==0.5.1
    - wrapt==1.16.0
prefix: /home/huan1932/.conda/envs/tarfa
